import os

CONST_MONGO_URL = os.environ.get('CONST_MONGO_URL')
CONST_DATABASE = os.environ.get('CONST_DATABASE')
CONST_ACCOUNT_COLLECTION = os.environ.get('CONST_ACCOUNT_COLLECTION')
CONST_TRANSACTION_COLLECTION = os.environ.get('CONST_TRANSACTION_COLLECTION')

TOKEN_SECRET = os.environ.get('TOKEN_SECRET')

# 30 days
JWT_EXPIRATION = 86400*30 